### ISSUE TITLE
Executor failed to create kernel. Unimplemented: Cast string to float is not supported      [[Node: Adam/apply_grad_op_0/update_FullyConnected_1/b/Cast_2 = Cast[DstT=DT_FLOAT, SrcT

### ISSUE THREAD

**Issue by wunengguang** [jhole89/classifying-cancer#1]
hello ,sir 
I have same error like this .But i cannot find how to slove this problem ,
my problem is below 👍 
 Unimplemented: Cast float to string is not supportedExecutor failed to create kernel，[[Node: Cast = Cast[DstT=DT_STRING, SrcT=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](Cast/x)]]

But my code executor other computer  Successfuly

**Comment by jhole89** [comment]
@wunengguang Thanks for checking this repo out. I'm unsure of this error, can you please post the full stack trace along with what command you ran so I can try and recreate this issue on my side?

**Comment by jhole89** [comment]
Closing issue as no information to replicate issue
