### ISSUE TITLE
Update code

### ISSUE THREAD

**Issue by SaharMSD111** [jhole89/classifying-cancer#3]
Hi there
Some attribute of TensorFlow that you used in codes no longer exists and gives an error.
would you help me in this regard?

**Comment by jhole89** [comment]
Hey @SaharMSD111, unfortunately this is a rather old project and as per the [README](https://github.com/jhole89/classifying-cancer#contributing) I'm not actively maintaining it and don't currently have capacity to do so. If you'd like to patch it up and issue a PR I'd happily review it.
